bq-dbt-zoomcamp:
  outputs:
    dev:
      dataset: stocks_dbt
      fixed_retries: 1
      keyfile: /.google/credentials/google_credentials.json
      method: service-account
      priority: interactive
      project: sylvan-earth-454218-d0
      threads: 4
      timeout_seconds: 300
      type: bigquery
  target: dev